# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65a7174d6af9bbdb366c5cae0102e02aaada117312629b8c32f22fdf2e1017cfc39ffd088dccfcd6d31116fe095471ffb9abded317980750148b93fde86b534f

test:
  secret_key_base: 8f781b4bdb7ff6f3c15454cf89a850463d1095c8919cac6f1fa3777bdc2cbd5ceba5ef85a9878ad630c316652fb52dcb09a32ee27b2f3a1d3e011232d6ca1878

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
